package parser

import "strings"

// Directional maps directional words to their abbreviations
var Directional = map[string]string{
	"north":     "N",
	"northeast": "NE",
	"east":      "E",
	"southeast": "SE",
	"south":     "S",
	"southwest": "SW",
	"west":      "W",
	"northwest": "NW",
}

// StreetType maps street type variations to standard abbreviations
var StreetType = map[string]string{
	"allee": "aly", "alley": "aly", "ally": "aly",
	"anex": "anx", "annex": "anx", "annx": "anx",
	"arcade": "arc",
	"av": "ave", "aven": "ave", "avenu": "ave", "avenue": "ave", "avn": "ave", "avnue": "ave",
	"bayoo": "byu", "bayou": "byu",
	"beach": "bch",
	"bend": "bnd",
	"bluf": "blf", "bluff": "blf",
	"bluffs": "blfs",
	"bot": "btm", "bottm": "btm", "bottom": "btm",
	"boul": "blvd", "boulevard": "blvd", "boulv": "blvd",
	"branch": "br", "brnch": "br",
	"brdge": "brg", "bridge": "brg",
	"brook": "brk",
	"brooks": "brks",
	"burg": "bg",
	"burgs": "bgs",
	"bypa": "byp", "bypas": "byp", "bypass": "byp", "byps": "byp",
	"camp": "cp", "cmp": "cp",
	"canyn": "cyn", "canyon": "cyn", "cnyn": "cyn",
	"cape": "cpe",
	"causeway": "cswy", "causway": "cswy", "causwa": "cswy",
	"cen": "ctr", "cent": "ctr", "center": "ctr", "centr": "ctr", "centre": "ctr", "cnter": "ctr", "cntr": "ctr",
	"centers": "ctrs",
	"circ": "cir", "circl": "cir", "circle": "cir", "crcl": "cir", "crcle": "cir",
	"circles": "cirs",
	"ck": "crk", "cr": "crk", "creek": "crk",
	"cliff": "clf",
	"cliffs": "clfs",
	"club": "clb",
	"common": "cmn",
	"commons": "cmns",
	"corner": "cor",
	"corners": "cors",
	"course": "crse",
	"court": "ct", "crt": "ct",
	"courts": "cts",
	"cove": "cv",
	"coves": "cvs",
	"crecent": "cres", "crescent": "cres", "cresent": "cres", "crscnt": "cres", "crsent": "cres", "crsnt": "cres",
	"crest": "crst",
	"crossing": "xing", "crssing": "xing", "crssng": "xing",
	"crossroad": "xrd",
	"crossroads": "xrds",
	"curve": "curv",
	"dale": "dl",
	"dam": "dm",
	"div": "dv", "divide": "dv", "dvd": "dv",
	"driv": "dr", "drive": "dr", "drv": "dr",
	"drives": "drs",
	"estate": "est",
	"estates": "ests",
	"exp": "expy", "expr": "expy", "express": "expy", "expressway": "expy", "expw": "expy",
	"extension": "ext", "extn": "ext", "extnsn": "ext",
	"extensions": "exts",
	"fall": "fall",
	"falls": "fls",
	"ferry": "fry", "frry": "fry",
	"field": "fld",
	"fields": "flds",
	"flat": "flt",
	"flats": "flts",
	"ford": "frd",
	"fords": "frds",
	"forest": "frst", "forests": "frst",
	"forg": "frg", "forge": "frg",
	"forges": "frgs",
	"fork": "frk",
	"forks": "frks",
	"fort": "ft", "frt": "ft",
	"freeway": "fwy", "freewy": "fwy", "frway": "fwy", "frwy": "fwy",
	"garden": "gdn", "gardn": "gdn", "grden": "gdn", "grdn": "gdn",
	"gardens": "gdns", "grdns": "gdns",
	"gateway": "gtwy", "gatewy": "gtwy", "gatway": "gtwy", "gtway": "gtwy",
	"glen": "gln",
	"glens": "glns",
	"green": "grn",
	"greens": "grns",
	"grov": "grv", "grove": "grv",
	"groves": "grvs",
	"harb": "hbr", "harbor": "hbr", "harbors": "hbrs", "harbr": "hbr", "hrbor": "hbr",
	"haven": "hvn", "havn": "hvn",
	"height": "hts", "heights": "hts", "hgts": "hts", "ht": "hts",
	"highway": "hwy", "highwy": "hwy", "hiway": "hwy", "hiwy": "hwy", "hway": "hwy",
	"hill": "hl",
	"hills": "hls",
	"hllw": "holw", "hollow": "holw", "hollows": "holw", "holws": "holw",
	"inlet": "inlt",
	"island": "is", "islnd": "is",
	"islands": "iss", "islnds": "iss",
	"isle": "isle",
	"isles": "isle",
	"jction": "jct", "jctn": "jct", "junction": "jct", "junctn": "jct", "juncton": "jct",
	"junctions": "jcts", "jctns": "jcts",
	"key": "ky",
	"keys": "kys",
	"knol": "knl", "knoll": "knl",
	"knolls": "knls",
	"la": "ln", "lane": "ln", "lanes": "ln",
	"lake": "lk",
	"lakes": "lks",
	"land": "land",
	"landing": "lndg", "lndng": "lndg",
	"ldge": "ldg", "lodg": "ldg", "lodge": "ldg",
	"light": "lgt",
	"lights": "lgts",
	"loaf": "lf",
	"lock": "lck",
	"locks": "lcks",
	"loop": "loop", "loops": "loop",
	"mall": "mall",
	"manor": "mnr",
	"manors": "mnrs",
	"meadow": "mdw",
	"meadows": "mdws", "medows": "mdws",
	"mews": "mews",
	"mill": "ml",
	"mills": "mls",
	"mission": "msn", "missn": "msn", "mssn": "msn",
	"mnt": "mt", "mount": "mt",
	"mntain": "mtn", "mntn": "mtn", "mountain": "mtn", "mountin": "mtn", "mtin": "mtn",
	"mountains": "mtns", "mntns": "mtns",
	"motorway": "mtwy",
	"neck": "nck",
	"orchard": "orch", "orchrd": "orch",
	"overpass": "opas",
	"ovl": "oval",
	"park": "park", "pk": "park", "prk": "park",
	"parks": "park",
	"parkway": "pkwy", "parkways": "pkwy", "parkwy": "pkwy", "pkway": "pkwy", "pkwys": "pkwy", "pky": "pkwy",
	"pass": "pass",
	"passage": "psge",
	"path": "path", "paths": "path",
	"pike": "pike", "pikes": "pike",
	"pine": "pne",
	"pines": "pnes",
	"place": "pl",
	"plain": "pln",
	"plains": "plns", "plaines": "plns",
	"plaza": "plz", "plza": "plz",
	"point": "pt",
	"points": "pts",
	"port": "prt",
	"ports": "prts",
	"prairie": "pr", "prarie": "pr", "prr": "pr",
	"rad": "radl", "radial": "radl", "radiel": "radl",
	"ranch": "rnch", "ranches": "rnch", "rnchs": "rnch",
	"rapid": "rpd",
	"rapids": "rpds",
	"rdge": "rdg", "ridge": "rdg",
	"ridges": "rdgs",
	"rest": "rst",
	"river": "riv", "rivr": "riv", "rvr": "riv",
	"road": "rd",
	"roads": "rds",
	"route": "rte",
	"row": "row",
	"rue": "rue",
	"run": "run",
	"shoal": "shl",
	"shoals": "shls",
	"shoar": "shr", "shore": "shr",
	"shoars": "shrs", "shores": "shrs",
	"skyway": "skwy",
	"spng": "spg", "spring": "spg", "sprng": "spg",
	"spngs": "spgs", "springs": "spgs", "sprngs": "spgs",
	"spur": "spur", "spurs": "spur",
	"sqr": "sq", "sqre": "sq", "squ": "sq", "square": "sq",
	"sqrs": "sqs", "squares": "sqs",
	"station": "sta", "statn": "sta", "stn": "sta",
	"str": "st", "street": "st", "strt": "st",
	"streets": "sts",
	"strav": "stra", "strave": "stra", "straven": "stra", "stravenue": "stra", "stravn": "stra", "strvn": "stra", "strvnue": "stra",
	"stream": "strm", "streme": "strm",
	"sumit": "smt", "sumitt": "smt", "summit": "smt",
	"terr": "ter", "terrace": "ter",
	"throughway": "trwy",
	"tpk": "tpke", "trnpk": "tpke", "trpk": "tpke", "turnpike": "tpke", "turnpk": "tpke",
	"tr": "trl", "trail": "trl", "trails": "trl", "trls": "trl",
	"trace": "trce", "traces": "trce",
	"track": "trak", "tracks": "trak", "trk": "trak", "trks": "trak",
	"trafficway": "trfy",
	"tunel": "tunl", "tunls": "tunl", "tunnel": "tunl", "tunnels": "tunl", "tunnl": "tunl",
	"underpass": "upas",
	"union": "un",
	"unions": "uns",
	"valley": "vly", "vally": "vly", "vlly": "vly",
	"valleys": "vlys",
	"vdct": "via", "viadct": "via", "viaduct": "via",
	"view": "vw",
	"views": "vws",
	"vill": "vlg", "villag": "vlg", "village": "vlg", "villg": "vlg", "villiage": "vlg",
	"villages": "vlgs",
	"ville": "vl",
	"vist": "vis", "vista": "vis", "vst": "vis", "vsta": "vis",
	"wall": "wall",
	"walk": "walk", "walks": "walk",
	"well": "wl",
	"wells": "wls",
	"wy": "way",
}

// StateCode maps state names to their two-letter abbreviations
var StateCode = map[string]string{
	"alabama":                        "AL",
	"alaska":                         "AK",
	"american samoa":                 "AS",
	"arizona":                        "AZ",
	"arkansas":                       "AR",
	"california":                     "CA",
	"colorado":                       "CO",
	"connecticut":                    "CT",
	"delaware":                       "DE",
	"district of columbia":           "DC",
	"federated states of micronesia": "FM",
	"florida":                        "FL",
	"georgia":                        "GA",
	"guam":                           "GU",
	"hawaii":                         "HI",
	"idaho":                          "ID",
	"illinois":                       "IL",
	"indiana":                        "IN",
	"iowa":                           "IA",
	"kansas":                         "KS",
	"kentucky":                       "KY",
	"louisiana":                      "LA",
	"maine":                          "ME",
	"marshall islands":               "MH",
	"maryland":                       "MD",
	"massachusetts":                  "MA",
	"michigan":                       "MI",
	"minnesota":                      "MN",
	"mississippi":                    "MS",
	"missouri":                       "MO",
	"montana":                        "MT",
	"nebraska":                       "NE",
	"nevada":                         "NV",
	"new hampshire":                  "NH",
	"new jersey":                     "NJ",
	"new mexico":                     "NM",
	"new york":                       "NY",
	"north carolina":                 "NC",
	"north dakota":                   "ND",
	"northern mariana islands":       "MP",
	"ohio":                           "OH",
	"oklahoma":                       "OK",
	"oregon":                         "OR",
	"palau":                          "PW",
	"pennsylvania":                   "PA",
	"puerto rico":                    "PR",
	"rhode island":                   "RI",
	"south carolina":                 "SC",
	"south dakota":                   "SD",
	"tennessee":                      "TN",
	"texas":                          "TX",
	"utah":                           "UT",
	"vermont":                        "VT",
	"virgin islands":                 "VI",
	"virginia":                       "VA",
	"washington":                     "WA",
	"west virginia":                  "WV",
	"wisconsin":                      "WI",
	"wyoming":                        "WY",
}

// SecondaryUnitTypes are common apartment/suite designators
var SecondaryUnitTypes = []string{
	"apartment", "apt",
	"basement", "bsmt",
	"building", "bldg",
	"department", "dept",
	"floor", "fl",
	"front",
	"hanger", "hngr",
	"key",
	"lobby", "lbby",
	"lot",
	"lower", "lowr",
	"office", "ofc",
	"penthouse", "ph",
	"pier",
	"rear",
	"room", "rm",
	"side",
	"slip",
	"space", "spc",
	"stop",
	"suite", "ste",
	"trailer", "trlr",
	"unit",
	"upper", "uppr",
	"#",
}

// NormalizeDirectional normalizes directional words
func NormalizeDirectional(dir string) string {
	dir = strings.ToLower(strings.TrimSpace(dir))
	if abbr, ok := Directional[dir]; ok {
		return abbr
	}
	// Already an abbreviation
	dir = strings.ToUpper(dir)
	for _, v := range Directional {
		if v == dir {
			return dir
		}
	}
	return ""
}

// NormalizeStreetType normalizes street type words
func NormalizeStreetType(streetType string) string {
	streetType = strings.ToLower(strings.TrimSpace(streetType))
	if abbr, ok := StreetType[streetType]; ok {
		return abbr
	}
	// Already an abbreviation
	streetType = strings.ToLower(streetType)
	for _, v := range StreetType {
		if v == streetType {
			return streetType
		}
	}
	return streetType
}

// NormalizeState normalizes state names to two-letter codes
func NormalizeState(state string) string {
	state = strings.ToLower(strings.TrimSpace(state))
	if code, ok := StateCode[state]; ok {
		return code
	}
	// Check if already a valid state code
	state = strings.ToUpper(state)
	for _, v := range StateCode {
		if v == state {
			return state
		}
	}
	return ""
}
